# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: –’≈·µƒ
email: decemberpei@gmail.com
description:  ÀÊ±„–¥µ„ ≤√¥
#baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "http://decemberpei.github.io" # the base hostname & protocol for your site
twitter_username: decemberpei
github_username:  decemberpei

# Build settings
markdown: kramdown
